# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'b5c6bc0c-cc4b-4e58-8bd5-daab70b4a2c2'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/KeePass.Tests/*.csproj'
    testRunTitle: 'Standard test'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/KeePass/*.csproj'
    versioningScheme: byPrereleaseNumber
    includeSymbols: true
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'b5c6bc0c-cc4b-4e58-8bd5-daab70b4a2c2'
    allowPackageConflicts: true